# Use Linux (Android not supported on macOS)
os: linux
dist: jammy

language: android
jdk: openjdk17

android:
  components:
    - build-tools-35.0.0
    - android-36
    - platform-tools

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

env:
  global:
    - ANDROID_HOME=$HOME/android-sdk
    - PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
    - KEYSTORE_PATH=$HOME/.android/debug.keystore
    - KEYSTORE_ALIAS=androiddebugkey
    - KEYSTORE_PASS=android
    # 🔥 Replace this with your actual Firebase App ID
    - FIREBASE_APP_ID=1:118480560883:android:fde2210fc957ab444acd86

before_install:
  - chmod +x gradlew
  - |
    if [ ! -f "$KEYSTORE_PATH" ]; then
      echo "Debug keystore not found. Creating one..."
      mkdir -p $HOME/.android
      keytool -genkeypair -v -keystore $KEYSTORE_PATH -alias $KEYSTORE_ALIAS \
        -storepass $KEYSTORE_PASS -keypass $KEYSTORE_PASS -dname "CN=Android Debug,O=Android,C=US" \
        -keyalg RSA -keysize 2048 -validity 10000
    else
      echo "Debug keystore already exists."
    fi

script:
  - ./gradlew clean
  - echo "Running Robolectric + unit tests..."
  - ./gradlew testDebugUnitTest

  - echo "Building APK..."
  - ./gradlew assembleDebug

  - echo "Generating SHA-1 key..."
  - keytool -list -v -keystore $KEYSTORE_PATH -alias $KEYSTORE_ALIAS \
    -storepass $KEYSTORE_PASS -keypass $KEYSTORE_PASS | grep "SHA1" || true

# ✅ Deploy to Firebase App Distribution
after_success:
  # Install Firebase CLI
  - curl -sL https://firebase.tools | bash
  # Upload the debug APK to Firebase App Distribution
  - echo "Uploading APK to Firebase App Distribution..."
  - firebase appdistribution:distribute app/build/outputs/apk/debug/app-debug.apk \
    --app $FIREBASE_APP_ID \
    --token $FIREBASE_TOKEN \
    --groups "qa-group" \
    --release-notes "Automated build from Travis CI"

